// Generated by creative_core.contracts.export_all — do not edit by hand.
// core_version 1.1.0 · schema_version 1

export type ProductMode = "single_product" | "multi_product";
export type PublicStrategy = "CLEAN_ANGLES" | "REMARKETING" | "FUNNEL_VISUAL";
export type AngleId = "IDENTIDADE_ORIGEM" | "LIFESTYLE_COTIDIANO" | "ORGULHO_DISCRETO" | "PERTENCIMENTO" | "NOSTALGIA_ORIGEM" | "CABIDE" | "PRODUTO_ESTAMPA" | "CAIMENTO" | "CLOSE_ESTAMPA" | "CLOSE_BOLSO" | "PREMIUM_ESTILO" | "CREATOR_STYLE" | "PRESENTE_AFETO";

export interface Persona {
  id?: string;
  label: string;
  age_range?: string;
  appearance?: string;
  style?: string;
  behavior?: string;
  notes?: string;
  source?: "automatic" | "custom";
}

export interface BrandKit {
  id: string;
  name: string;
  description?: string;
  positioning?: Array<string>;
  audience?: Array<string>;
  tone?: Array<string>;
  visualStyle?: Array<string>;
  colors?: Array<string>;
  typographyNotes?: Array<string>;
  preferredContexts?: Array<string>;
  avoid?: Array<string>;
  manualNotes?: Array<string>;
  enabledAngles?: Array<"IDENTIDADE_ORIGEM" | "LIFESTYLE_COTIDIANO" | "ORGULHO_DISCRETO" | "PERTENCIMENTO" | "NOSTALGIA_ORIGEM" | "CABIDE" | "PRODUTO_ESTAMPA" | "CAIMENTO" | "CLOSE_ESTAMPA" | "CLOSE_BOLSO" | "PREMIUM_ESTILO" | "CREATOR_STYLE" | "PRESENTE_AFETO">;
  angleLabels?: Record<string, string>;
  headlineStyle?: Array<string>;
  ctaStyle?: Array<string>;
  strategyRules?: Record<string, unknown>;
  defaultNicheKitId?: string;
  defaultContextProvider?: "geographic" | "niche" | "custom";
  suggestedPersonas?: Array<Persona>;
  schemaVersion: number;
  version: number;
}

export interface NicheKit {
  id: string;
  name: string;
  audienceBehaviors?: Array<string>;
  commonUsageScenarios?: Array<string>;
  activities?: Array<string>;
  sceneContexts?: Array<string>;
  materials?: Array<string>;
  visualCliches?: Array<string>;
  avoid?: Array<string>;
  recommendedAngles?: Array<"IDENTIDADE_ORIGEM" | "LIFESTYLE_COTIDIANO" | "ORGULHO_DISCRETO" | "PERTENCIMENTO" | "NOSTALGIA_ORIGEM" | "CABIDE" | "PRODUTO_ESTAMPA" | "CAIMENTO" | "CLOSE_ESTAMPA" | "CLOSE_BOLSO" | "PREMIUM_ESTILO" | "CREATOR_STYLE" | "PRESENTE_AFETO">;
  strategyRules?: Record<string, unknown>;
  angleLabels?: Record<string, string>;
  productTypes?: Array<string>;
  supportsApparelAngles?: boolean;
  suggestedPersonas?: Array<Persona>;
  schemaVersion: number;
  version: number;
}

export interface ContextSubject {
  name: string;
  metadata?: Record<string, unknown>;
}

export interface ContextProfile {
  contextId: string;
  contextType: "geographic" | "niche" | "custom" | "bond" | "neutral";
  subject: ContextSubject;
  summary?: string;
  sceneContexts?: Array<string>;
  visualSignatures?: Array<string>;
  activities?: Array<string>;
  materials?: Array<string>;
  environment?: Array<string>;
  domainElements?: Array<string>;
  avoid?: Array<string>;
  sources?: Array<string>;
  confidence?: number;
  status: "draft" | "approved" | "rejected";
  schemaVersion: number;
  promptVersion: number;
  profileVersion: number;
}

export interface CreativeProduct {
  id: string;
  brandId?: string;
  name: string;
  type: string;
  description?: string;
  referenceImages: Array<string>;
  metadata?: Record<string, unknown>;
}

export interface Angle {
  id: "IDENTIDADE_ORIGEM" | "LIFESTYLE_COTIDIANO" | "ORGULHO_DISCRETO" | "PERTENCIMENTO" | "NOSTALGIA_ORIGEM" | "CABIDE" | "PRODUTO_ESTAMPA" | "CAIMENTO" | "CLOSE_ESTAMPA" | "CLOSE_BOLSO" | "PREMIUM_ESTILO" | "CREATOR_STYLE" | "PRESENTE_AFETO";
  label: string;
  description?: string;
  uses_person: boolean;
  apparel_only: boolean;
  multi_product_limit: number;
}

export interface Placement {
  id: "FEED_4X5" | "STORY_9X16";
  label: string;
  width: number;
  height: number;
  api_size: string;
}

export interface ContextSelection {
  mode: "automatic" | "geographic" | "niche" | "custom";
  profile?: ContextProfile;
  subject?: ContextSubject;
  context_id?: string;
}

export interface RemarketingOptions {
  intent: "site_visitor" | "product_view" | "collection_discovery" | "cart" | "checkout" | "social_proof" | "objection";
  products_source?: "catalog" | "basket";
  stage_override?: "TOFU" | "MOFU" | "BOFU";
  text_density?: "minimal" | "balanced" | "commercial";
  cta_emphasis?: "subtle" | "medium" | "strong";
  clean_mode?: "auto" | "always" | "never";
  headline?: string;
  subheadline?: string;
  cta?: string;
  benefits?: Array<string>;
  social_proof_facts?: Array<string>;
}

export interface FunnelOptions {
  headline?: string;
  subheadline?: string;
  cta?: string;
  badges?: Array<string>;
  benefits?: Array<string>;
  search_bar_text?: string;
  chips?: Array<string>;
  text_density?: "minimal" | "balanced" | "commercial";
  cta_emphasis?: "subtle" | "medium" | "strong";
  clean_mode?: boolean;
}

export interface CopyOptions {
  generate: boolean;
  funnel_stages?: Array<"TOFU" | "MOFU" | "BOFU">;
}

export interface HistoryHints {
  recent_scenes?: Array<string>;
  recent_personas?: Array<string>;
}

export interface CreativeRequest {
  creative_id?: string;
  strategy: "CLEAN_ANGLES" | "REMARKETING" | "FUNNEL_VISUAL";
  product_mode: "single_product" | "multi_product";
  products: Array<CreativeProduct>;
  brand_kit?: BrandKit;
  brand_kit_id?: string;
  niche_kit?: NicheKit;
  niche_kit_id?: string;
  angle_id: "IDENTIDADE_ORIGEM" | "LIFESTYLE_COTIDIANO" | "ORGULHO_DISCRETO" | "PERTENCIMENTO" | "NOSTALGIA_ORIGEM" | "CABIDE" | "PRODUTO_ESTAMPA" | "CAIMENTO" | "CLOSE_ESTAMPA" | "CLOSE_BOLSO" | "PREMIUM_ESTILO" | "CREATOR_STYLE" | "PRESENTE_AFETO";
  placement_id: "FEED_4X5" | "STORY_9X16";
  persona_mode?: "automatic" | "custom" | "none";
  persona?: Persona;
  context?: ContextSelection;
  funnel_stage?: "TOFU" | "MOFU" | "BOFU";
  remarketing?: RemarketingOptions;
  funnel?: FunnelOptions;
  copy?: CopyOptions;
  quality?: "low" | "medium" | "high";
  seed?: number;
  history_hints?: HistoryHints;
  prompt_version?: number;
}

export interface KitRef {
  id: string;
  version: number;
}

export interface ResolvedContext {
  context_id: string;
  context_type: "geographic" | "niche" | "custom" | "bond" | "neutral";
  provider: string;
  scene: string;
  supporting_element?: string | null;
  avoid?: Array<string>;
  status: "draft" | "approved" | "rejected";
  profile_version: number;
}

export interface OverlaySpec {
  allowed: boolean;
  headline?: string | null;
  subheadline?: string | null;
  cta?: string | null;
  badges?: Array<string>;
  benefits?: Array<string>;
  search_bar_text?: string | null;
  chips?: Array<string>;
  text_density?: "minimal" | "balanced" | "commercial" | null;
  cta_emphasis?: "subtle" | "medium" | "strong" | null;
  clean: boolean;
}

export interface ReferenceRole {
  ref: string;
  product_id: string;
  role: "product_art" | "layout_only";
  order: number;
}

export interface PromptSection {
  name: string;
  length: number;
}

export interface PromptInfo {
  text: string;
  sections: Array<PromptSection>;
  sha256: string;
  prompt_version: number;
}

export interface ModelSelection {
  task: string;
  model: string;
  quality: "low" | "medium" | "high";
  size: string;
}

export interface ValidationCheck {
  rule: string;
  passed: boolean;
}

export interface CreativePlan {
  plan_id: string;
  creative_id: string;
  schema_version: number;
  strategy: "CLEAN_ANGLES" | "REMARKETING" | "FUNNEL_VISUAL";
  internal_strategy_id: string;
  product_mode: "single_product" | "multi_product";
  products: Array<CreativeProduct>;
  angle: Angle;
  placement: Placement;
  persona?: Persona | null;
  context: ResolvedContext;
  brand_kit: KitRef;
  niche_kit: KitRef;
  funnel_stage?: "TOFU" | "MOFU" | "BOFU" | null;
  remarketing_intent?: "site_visitor" | "product_view" | "collection_discovery" | "cart" | "checkout" | "social_proof" | "objection" | null;
  layout?: string | null;
  overlay: OverlaySpec;
  copy: CopyOptions;
  references: Array<ReferenceRole>;
  prompt: PromptInfo;
  model: ModelSelection;
  versions: Record<string, unknown>;
  validations: Array<ValidationCheck>;
  warnings: Array<string>;
}

export interface GenerationError {
  code: string;
  message: string;
  retryable: boolean;
  cause: string;
  details?: Record<string, unknown>;
}

export interface AssetInfo {
  mime_type: string;
  width: number;
  height: number;
  byte_size: number;
  sha256: string;
  data_base64: string;
}

export interface CreativeResult {
  creative_id: string;
  plan_id: string;
  status: "completed" | "failed";
  generation_attempt: number;
  asset?: AssetInfo | null;
  metadata: Record<string, unknown>;
  versions: Record<string, unknown>;
  error?: GenerationError | null;
  created_at: string;
}

export interface CopyVariant {
  funnel_stage: "TOFU" | "MOFU" | "BOFU";
  primary_text: string;
  headline: string;
  description: string;
}

export interface GenerationRecord {
  creative_id: string;
  strategy: string;
  internal_strategy_id?: string | null;
  product_mode?: string | null;
  product_ids?: Array<string> | null;
  angle?: string | null;
  context?: string | null;
  persona?: string | null;
  placement?: string | null;
  brand_kit?: string | null;
  niche_kit?: string | null;
  funnel_stage?: string | null;
  remarketing_intent?: string | null;
  quality?: string | null;
  asset?: string | null;
  schema_version?: number | null;
  prompt_version?: number | null;
  brand_kit_version?: number | null;
  niche_kit_version?: number | null;
  context_profile_version?: number | null;
  strategy_version?: number | null;
  core_version?: string | null;
  extra?: Record<string, unknown> | null;
  created_at: string;
}
