-- Fase 1 · reverte colunas
-- GERADO por scripts/tenancy/gerar-sql-fase1.mjs a partir de lib/platform/tenancy-manifest.js.
-- Congelado: edite o manifesto e regenere só se o desenho mudar ANTES do primeiro deploy.

DROP FUNCTION IF EXISTS tenancy_problemas_de_ownership();
DROP FUNCTION IF EXISTS tenancy_exigir_cobertura();
DROP FUNCTION IF EXISTS tenancy_itens_sem_mapeamento();
ALTER TABLE bulk_category_jobs DROP COLUMN IF EXISTS organization_id;
ALTER TABLE campaigns DROP COLUMN IF EXISTS organization_id;
ALTER TABLE controle_estoque_observacoes DROP COLUMN IF EXISTS organization_id;
ALTER TABLE despesas_operacionais DROP COLUMN IF EXISTS organization_id;
ALTER TABLE estoque_observacoes DROP COLUMN IF EXISTS organization_id;
ALTER TABLE ga4_performance_cache DROP COLUMN IF EXISTS organization_id;
ALTER TABLE google_analytics_connections DROP COLUMN IF EXISTS organization_id;
ALTER TABLE pedidos_backfill_jobs DROP COLUMN IF EXISTS organization_id;
ALTER TABLE pedidos_ink DROP COLUMN IF EXISTS organization_id;
ALTER TABLE pedidos_ink_itens DROP COLUMN IF EXISTS organization_id;
ALTER TABLE produtos_feed DROP COLUMN IF EXISTS organization_id;
ALTER TABLE produtos_feed_sync DROP COLUMN IF EXISTS organization_id;
ALTER TABLE produtos_ink DROP COLUMN IF EXISTS organization_id;
ALTER TABLE produtos_ink_sync DROP COLUMN IF EXISTS organization_id;
ALTER TABLE sync_estado DROP COLUMN IF EXISTS organization_id;
ALTER TABLE utm_campaigns DROP COLUMN IF EXISTS organization_id;
ALTER TABLE origens_migration_city_uf_map DROP COLUMN IF EXISTS organization_id;
ALTER TABLE origens_migration_rules DROP COLUMN IF EXISTS organization_id;
ALTER TABLE origens_migration_simulations DROP COLUMN IF EXISTS organization_id;
ALTER TABLE audit_log DROP COLUMN IF EXISTS organization_id;
ALTER TABLE media_assets DROP COLUMN IF EXISTS organization_id;
ALTER TABLE webhook_eventos DROP COLUMN IF EXISTS organization_id;
ALTER TABLE whatsapp_web_outbox DROP COLUMN IF EXISTS organization_id;
ALTER TABLE bulk_category_job_items DROP COLUMN IF EXISTS organization_id;
ALTER TABLE campaign_recipients DROP COLUMN IF EXISTS organization_id;
ALTER TABLE origens_migration_simulation_items DROP COLUMN IF EXISTS organization_id;
ALTER TABLE app_config DROP COLUMN IF EXISTS organization_id;
ALTER TABLE custos_api_precos DROP COLUMN IF EXISTS organization_id;
ALTER TABLE segments DROP COLUMN IF EXISTS organization_id;
ALTER TABLE utm_presets DROP COLUMN IF EXISTS organization_id;
ALTER TABLE whatsapp_web_mensagens DROP COLUMN IF EXISTS organization_id;
ALTER TABLE meta_connections DROP COLUMN IF EXISTS organization_id;
ALTER TABLE meta_ad_accounts DROP COLUMN IF EXISTS organization_id;
ALTER TABLE meta_campaigns DROP COLUMN IF EXISTS organization_id;
ALTER TABLE meta_adsets DROP COLUMN IF EXISTS organization_id;
ALTER TABLE meta_ads DROP COLUMN IF EXISTS organization_id;
ALTER TABLE meta_creatives DROP COLUMN IF EXISTS organization_id;
ALTER TABLE meta_insights_daily DROP COLUMN IF EXISTS organization_id;
ALTER TABLE meta_sync_logs DROP COLUMN IF EXISTS organization_id;
ALTER TABLE google_ads_connections DROP COLUMN IF EXISTS organization_id;
ALTER TABLE google_ads_customers DROP COLUMN IF EXISTS organization_id;
ALTER TABLE google_ads_campaigns DROP COLUMN IF EXISTS organization_id;
ALTER TABLE google_ads_insights_daily DROP COLUMN IF EXISTS organization_id;
ALTER TABLE google_ads_sync_logs DROP COLUMN IF EXISTS organization_id;
ALTER TABLE creative_settings DROP COLUMN IF EXISTS organization_id;
ALTER TABLE creative_brand_profiles DROP COLUMN IF EXISTS organization_id;
ALTER TABLE creative_niche_profiles DROP COLUMN IF EXISTS organization_id;
ALTER TABLE creative_context_profiles DROP COLUMN IF EXISTS organization_id;
ALTER TABLE creative_personas DROP COLUMN IF EXISTS organization_id;
ALTER TABLE creative_products DROP COLUMN IF EXISTS organization_id;
ALTER TABLE creative_jobs DROP COLUMN IF EXISTS organization_id;
ALTER TABLE creative_generations DROP COLUMN IF EXISTS organization_id;
ALTER TABLE creative_assets DROP COLUMN IF EXISTS organization_id;
