-- Fase 1 · reverte constraints
-- GERADO por scripts/tenancy/gerar-sql-fase1.mjs a partir de lib/platform/tenancy-manifest.js.
-- Congelado: edite o manifesto e regenere só se o desenho mudar ANTES do primeiro deploy.

DROP INDEX IF EXISTS idx_creative_assets_org;
ALTER TABLE creative_assets ALTER COLUMN organization_id DROP NOT NULL;
ALTER TABLE creative_assets DROP CONSTRAINT IF EXISTS fk_creative_assets_org;
DROP INDEX IF EXISTS idx_creative_generations_org;
ALTER TABLE creative_generations ALTER COLUMN organization_id DROP NOT NULL;
ALTER TABLE creative_generations DROP CONSTRAINT IF EXISTS fk_creative_generations_org;
DROP INDEX IF EXISTS idx_creative_jobs_org;
ALTER TABLE creative_jobs ALTER COLUMN organization_id DROP NOT NULL;
ALTER TABLE creative_jobs DROP CONSTRAINT IF EXISTS fk_creative_jobs_org;
DROP INDEX IF EXISTS idx_creative_products_org;
ALTER TABLE creative_products ALTER COLUMN organization_id DROP NOT NULL;
ALTER TABLE creative_products DROP CONSTRAINT IF EXISTS fk_creative_products_org;
DROP INDEX IF EXISTS idx_creative_personas_org;
ALTER TABLE creative_personas ALTER COLUMN organization_id DROP NOT NULL;
ALTER TABLE creative_personas DROP CONSTRAINT IF EXISTS fk_creative_personas_org;
DROP INDEX IF EXISTS idx_creative_context_profiles_org;
ALTER TABLE creative_context_profiles ALTER COLUMN organization_id DROP NOT NULL;
ALTER TABLE creative_context_profiles DROP CONSTRAINT IF EXISTS fk_creative_context_profiles_org;
DROP INDEX IF EXISTS idx_creative_niche_profiles_org;
ALTER TABLE creative_niche_profiles ALTER COLUMN organization_id DROP NOT NULL;
ALTER TABLE creative_niche_profiles DROP CONSTRAINT IF EXISTS fk_creative_niche_profiles_org;
DROP INDEX IF EXISTS idx_creative_brand_profiles_org;
ALTER TABLE creative_brand_profiles ALTER COLUMN organization_id DROP NOT NULL;
ALTER TABLE creative_brand_profiles DROP CONSTRAINT IF EXISTS fk_creative_brand_profiles_org;
DROP INDEX IF EXISTS uq_creative_settings_org;
DROP INDEX IF EXISTS idx_creative_settings_org;
ALTER TABLE creative_settings ALTER COLUMN organization_id DROP NOT NULL;
ALTER TABLE creative_settings DROP CONSTRAINT IF EXISTS fk_creative_settings_org;
DROP INDEX IF EXISTS idx_google_ads_sync_logs_org;
ALTER TABLE google_ads_sync_logs ALTER COLUMN organization_id DROP NOT NULL;
ALTER TABLE google_ads_sync_logs DROP CONSTRAINT IF EXISTS fk_google_ads_sync_logs_org;
DROP INDEX IF EXISTS uq_google_ads_insights_daily_org;
DROP INDEX IF EXISTS idx_google_ads_insights_daily_org;
ALTER TABLE google_ads_insights_daily ALTER COLUMN organization_id DROP NOT NULL;
ALTER TABLE google_ads_insights_daily DROP CONSTRAINT IF EXISTS fk_google_ads_insights_daily_org;
DROP INDEX IF EXISTS uq_google_ads_campaigns_org;
DROP INDEX IF EXISTS idx_google_ads_campaigns_org;
ALTER TABLE google_ads_campaigns ALTER COLUMN organization_id DROP NOT NULL;
ALTER TABLE google_ads_campaigns DROP CONSTRAINT IF EXISTS fk_google_ads_campaigns_org;
DROP INDEX IF EXISTS uq_google_ads_customers_org;
DROP INDEX IF EXISTS uq_google_ads_customers_selecionada_org;
DROP INDEX IF EXISTS idx_google_ads_customers_org;
ALTER TABLE google_ads_customers ALTER COLUMN organization_id DROP NOT NULL;
ALTER TABLE google_ads_customers DROP CONSTRAINT IF EXISTS fk_google_ads_customers_org;
ALTER TABLE google_ads_connections ALTER COLUMN id DROP DEFAULT;
DROP SEQUENCE IF EXISTS google_ads_connections_id_seq;
ALTER TABLE google_ads_connections ADD CONSTRAINT google_ads_connections_id_check CHECK (id = 1);
DROP INDEX IF EXISTS uq_google_ads_connections_org;
DROP INDEX IF EXISTS idx_google_ads_connections_org;
ALTER TABLE google_ads_connections ALTER COLUMN organization_id DROP NOT NULL;
ALTER TABLE google_ads_connections DROP CONSTRAINT IF EXISTS fk_google_ads_connections_org;
DROP INDEX IF EXISTS idx_meta_sync_logs_org;
ALTER TABLE meta_sync_logs ALTER COLUMN organization_id DROP NOT NULL;
ALTER TABLE meta_sync_logs DROP CONSTRAINT IF EXISTS fk_meta_sync_logs_org;
DROP INDEX IF EXISTS uq_meta_insights_daily_org;
DROP INDEX IF EXISTS idx_meta_insights_daily_org;
ALTER TABLE meta_insights_daily ALTER COLUMN organization_id DROP NOT NULL;
ALTER TABLE meta_insights_daily DROP CONSTRAINT IF EXISTS fk_meta_insights_daily_org;
DROP INDEX IF EXISTS uq_meta_creatives_org;
DROP INDEX IF EXISTS idx_meta_creatives_org;
ALTER TABLE meta_creatives ALTER COLUMN organization_id DROP NOT NULL;
ALTER TABLE meta_creatives DROP CONSTRAINT IF EXISTS fk_meta_creatives_org;
DROP INDEX IF EXISTS uq_meta_ads_org;
DROP INDEX IF EXISTS idx_meta_ads_org;
ALTER TABLE meta_ads ALTER COLUMN organization_id DROP NOT NULL;
ALTER TABLE meta_ads DROP CONSTRAINT IF EXISTS fk_meta_ads_org;
DROP INDEX IF EXISTS uq_meta_adsets_org;
DROP INDEX IF EXISTS idx_meta_adsets_org;
ALTER TABLE meta_adsets ALTER COLUMN organization_id DROP NOT NULL;
ALTER TABLE meta_adsets DROP CONSTRAINT IF EXISTS fk_meta_adsets_org;
DROP INDEX IF EXISTS uq_meta_campaigns_org;
DROP INDEX IF EXISTS idx_meta_campaigns_org;
ALTER TABLE meta_campaigns ALTER COLUMN organization_id DROP NOT NULL;
ALTER TABLE meta_campaigns DROP CONSTRAINT IF EXISTS fk_meta_campaigns_org;
DROP INDEX IF EXISTS uq_meta_ad_accounts_org;
DROP INDEX IF EXISTS uq_meta_ad_accounts_selecionada_org;
DROP INDEX IF EXISTS idx_meta_ad_accounts_org;
ALTER TABLE meta_ad_accounts ALTER COLUMN organization_id DROP NOT NULL;
ALTER TABLE meta_ad_accounts DROP CONSTRAINT IF EXISTS fk_meta_ad_accounts_org;
ALTER TABLE meta_connections ALTER COLUMN id DROP DEFAULT;
DROP SEQUENCE IF EXISTS meta_connections_id_seq;
ALTER TABLE meta_connections ADD CONSTRAINT meta_connections_id_check CHECK (id = 1);
DROP INDEX IF EXISTS uq_meta_connections_org;
DROP INDEX IF EXISTS idx_meta_connections_org;
ALTER TABLE meta_connections ALTER COLUMN organization_id DROP NOT NULL;
ALTER TABLE meta_connections DROP CONSTRAINT IF EXISTS fk_meta_connections_org;
DROP INDEX IF EXISTS uq_wa_web_mensagens_nome_org;
DROP INDEX IF EXISTS idx_whatsapp_web_mensagens_org;
ALTER TABLE whatsapp_web_mensagens ALTER COLUMN organization_id DROP NOT NULL;
ALTER TABLE whatsapp_web_mensagens DROP CONSTRAINT IF EXISTS fk_whatsapp_web_mensagens_org;
DROP INDEX IF EXISTS idx_utm_presets_org;
ALTER TABLE utm_presets ALTER COLUMN organization_id DROP NOT NULL;
ALTER TABLE utm_presets DROP CONSTRAINT IF EXISTS fk_utm_presets_org;
DROP INDEX IF EXISTS idx_segments_org;
ALTER TABLE segments ALTER COLUMN organization_id DROP NOT NULL;
ALTER TABLE segments DROP CONSTRAINT IF EXISTS fk_segments_org;
DROP INDEX IF EXISTS uq_custos_api_precos_org;
DROP INDEX IF EXISTS idx_custos_api_precos_org;
ALTER TABLE custos_api_precos ALTER COLUMN organization_id DROP NOT NULL;
ALTER TABLE custos_api_precos DROP CONSTRAINT IF EXISTS fk_custos_api_precos_org;
DROP INDEX IF EXISTS uq_app_config_org;
DROP INDEX IF EXISTS idx_app_config_org;
ALTER TABLE app_config ALTER COLUMN organization_id DROP NOT NULL;
ALTER TABLE app_config DROP CONSTRAINT IF EXISTS fk_app_config_org;
DROP INDEX IF EXISTS idx_integrations_org;
ALTER TABLE integrations ALTER COLUMN organization_id DROP NOT NULL;
ALTER TABLE integrations DROP CONSTRAINT IF EXISTS fk_integrations_org;
DROP INDEX IF EXISTS uq_integration_secrets_org;
DROP INDEX IF EXISTS idx_integration_secrets_org;
ALTER TABLE integration_secrets ALTER COLUMN organization_id DROP NOT NULL;
ALTER TABLE integration_secrets DROP CONSTRAINT IF EXISTS fk_integration_secrets_org;
DROP INDEX IF EXISTS idx_origens_migration_simulation_items_org;
ALTER TABLE origens_migration_simulation_items ALTER COLUMN organization_id DROP NOT NULL;
ALTER TABLE origens_migration_simulation_items DROP CONSTRAINT IF EXISTS fk_origens_migration_simulation_items_org;
DROP INDEX IF EXISTS uq_campaign_recipients_org;
DROP INDEX IF EXISTS idx_campaign_recipients_org;
ALTER TABLE campaign_recipients ALTER COLUMN organization_id DROP NOT NULL;
ALTER TABLE campaign_recipients DROP CONSTRAINT IF EXISTS fk_campaign_recipients_org;
DROP INDEX IF EXISTS idx_bulk_category_job_items_org;
ALTER TABLE bulk_category_job_items ALTER COLUMN organization_id DROP NOT NULL;
ALTER TABLE bulk_category_job_items DROP CONSTRAINT IF EXISTS fk_bulk_category_job_items_org;
DROP INDEX IF EXISTS uq_wa_web_outbox_dedupe_org;
DROP INDEX IF EXISTS idx_whatsapp_web_outbox_org;
ALTER TABLE whatsapp_web_outbox ALTER COLUMN organization_id DROP NOT NULL;
ALTER TABLE whatsapp_web_outbox DROP CONSTRAINT IF EXISTS fk_whatsapp_web_outbox_org;
DROP INDEX IF EXISTS idx_webhook_eventos_org;
ALTER TABLE webhook_eventos ALTER COLUMN organization_id DROP NOT NULL;
ALTER TABLE webhook_eventos DROP CONSTRAINT IF EXISTS fk_webhook_eventos_org;
DROP INDEX IF EXISTS uq_media_assets_public_token_org;
DROP INDEX IF EXISTS idx_media_assets_org;
ALTER TABLE media_assets ALTER COLUMN organization_id DROP NOT NULL;
ALTER TABLE media_assets DROP CONSTRAINT IF EXISTS fk_media_assets_org;
DROP INDEX IF EXISTS idx_audit_log_org;
ALTER TABLE audit_log ALTER COLUMN organization_id DROP NOT NULL;
ALTER TABLE audit_log DROP CONSTRAINT IF EXISTS fk_audit_log_org;
DROP INDEX IF EXISTS idx_origens_migration_simulations_org;
ALTER TABLE origens_migration_simulations ALTER COLUMN organization_id DROP NOT NULL;
ALTER TABLE origens_migration_simulations DROP CONSTRAINT IF EXISTS fk_origens_migration_simulations_org;
DROP INDEX IF EXISTS idx_origens_migration_rules_org;
ALTER TABLE origens_migration_rules ALTER COLUMN organization_id DROP NOT NULL;
ALTER TABLE origens_migration_rules DROP CONSTRAINT IF EXISTS fk_origens_migration_rules_org;
DROP INDEX IF EXISTS uq_origens_city_uf_map_org;
DROP INDEX IF EXISTS idx_origens_migration_city_uf_map_org;
ALTER TABLE origens_migration_city_uf_map ALTER COLUMN organization_id DROP NOT NULL;
ALTER TABLE origens_migration_city_uf_map DROP CONSTRAINT IF EXISTS fk_origens_migration_city_uf_map_org;
DROP INDEX IF EXISTS idx_utm_campaigns_org;
ALTER TABLE utm_campaigns ALTER COLUMN organization_id DROP NOT NULL;
ALTER TABLE utm_campaigns DROP CONSTRAINT IF EXISTS fk_utm_campaigns_org;
DROP INDEX IF EXISTS uq_sync_estado_org;
DROP INDEX IF EXISTS idx_sync_estado_org;
ALTER TABLE sync_estado ALTER COLUMN organization_id DROP NOT NULL;
ALTER TABLE sync_estado DROP CONSTRAINT IF EXISTS fk_sync_estado_org;
DROP INDEX IF EXISTS uq_produtos_ink_sync_org;
DROP INDEX IF EXISTS idx_produtos_ink_sync_org;
ALTER TABLE produtos_ink_sync ALTER COLUMN organization_id DROP NOT NULL;
ALTER TABLE produtos_ink_sync DROP CONSTRAINT IF EXISTS fk_produtos_ink_sync_org;
DROP INDEX IF EXISTS uq_produtos_ink_org;
DROP INDEX IF EXISTS idx_produtos_ink_org;
ALTER TABLE produtos_ink ALTER COLUMN organization_id DROP NOT NULL;
ALTER TABLE produtos_ink DROP CONSTRAINT IF EXISTS fk_produtos_ink_org;
DROP INDEX IF EXISTS uq_produtos_feed_sync_org;
DROP INDEX IF EXISTS idx_produtos_feed_sync_org;
ALTER TABLE produtos_feed_sync ALTER COLUMN organization_id DROP NOT NULL;
ALTER TABLE produtos_feed_sync DROP CONSTRAINT IF EXISTS fk_produtos_feed_sync_org;
DROP INDEX IF EXISTS uq_produtos_feed_org;
DROP INDEX IF EXISTS idx_produtos_feed_org;
ALTER TABLE produtos_feed ALTER COLUMN organization_id DROP NOT NULL;
ALTER TABLE produtos_feed DROP CONSTRAINT IF EXISTS fk_produtos_feed_org;
DROP INDEX IF EXISTS uq_pedidos_ink_itens_org;
DROP INDEX IF EXISTS idx_pedidos_ink_itens_org;
ALTER TABLE pedidos_ink_itens ALTER COLUMN organization_id DROP NOT NULL;
ALTER TABLE pedidos_ink_itens DROP CONSTRAINT IF EXISTS fk_pedidos_ink_itens_org;
DROP INDEX IF EXISTS uq_pedidos_ink_org;
DROP INDEX IF EXISTS idx_pedidos_ink_org;
ALTER TABLE pedidos_ink ALTER COLUMN organization_id DROP NOT NULL;
ALTER TABLE pedidos_ink DROP CONSTRAINT IF EXISTS fk_pedidos_ink_org;
DROP INDEX IF EXISTS idx_pedidos_backfill_jobs_org;
ALTER TABLE pedidos_backfill_jobs ALTER COLUMN organization_id DROP NOT NULL;
ALTER TABLE pedidos_backfill_jobs DROP CONSTRAINT IF EXISTS fk_pedidos_backfill_jobs_org;
DROP INDEX IF EXISTS uq_google_analytics_connections_org;
DROP INDEX IF EXISTS idx_google_analytics_connections_org;
ALTER TABLE google_analytics_connections ALTER COLUMN organization_id DROP NOT NULL;
ALTER TABLE google_analytics_connections DROP CONSTRAINT IF EXISTS fk_google_analytics_connections_org;
DROP INDEX IF EXISTS uq_ga4_performance_cache_org;
DROP INDEX IF EXISTS idx_ga4_performance_cache_org;
ALTER TABLE ga4_performance_cache ALTER COLUMN organization_id DROP NOT NULL;
ALTER TABLE ga4_performance_cache DROP CONSTRAINT IF EXISTS fk_ga4_performance_cache_org;
DROP INDEX IF EXISTS idx_estoque_observacoes_org;
ALTER TABLE estoque_observacoes ALTER COLUMN organization_id DROP NOT NULL;
ALTER TABLE estoque_observacoes DROP CONSTRAINT IF EXISTS fk_estoque_observacoes_org;
DROP INDEX IF EXISTS idx_despesas_operacionais_org;
ALTER TABLE despesas_operacionais ALTER COLUMN organization_id DROP NOT NULL;
ALTER TABLE despesas_operacionais DROP CONSTRAINT IF EXISTS fk_despesas_operacionais_org;
DROP INDEX IF EXISTS idx_controle_estoque_observacoes_org;
ALTER TABLE controle_estoque_observacoes ALTER COLUMN organization_id DROP NOT NULL;
ALTER TABLE controle_estoque_observacoes DROP CONSTRAINT IF EXISTS fk_controle_estoque_observacoes_org;
DROP INDEX IF EXISTS idx_campaigns_org;
ALTER TABLE campaigns ALTER COLUMN organization_id DROP NOT NULL;
ALTER TABLE campaigns DROP CONSTRAINT IF EXISTS fk_campaigns_org;
DROP INDEX IF EXISTS idx_bulk_category_jobs_org;
ALTER TABLE bulk_category_jobs ALTER COLUMN organization_id DROP NOT NULL;
ALTER TABLE bulk_category_jobs DROP CONSTRAINT IF EXISTS fk_bulk_category_jobs_org;
