-- Fase 1 · reverte RLS
-- GERADO por scripts/tenancy/gerar-sql-fase1.mjs a partir de lib/platform/tenancy-manifest.js.
-- Congelado: edite o manifesto e regenere só se o desenho mudar ANTES do primeiro deploy.

DROP POLICY IF EXISTS tenancy_isolamento ON bulk_category_jobs;
ALTER TABLE bulk_category_jobs NO FORCE ROW LEVEL SECURITY;
ALTER TABLE bulk_category_jobs DISABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenancy_isolamento ON campaigns;
ALTER TABLE campaigns NO FORCE ROW LEVEL SECURITY;
ALTER TABLE campaigns DISABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenancy_isolamento ON controle_estoque_observacoes;
ALTER TABLE controle_estoque_observacoes NO FORCE ROW LEVEL SECURITY;
ALTER TABLE controle_estoque_observacoes DISABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenancy_isolamento ON despesas_operacionais;
ALTER TABLE despesas_operacionais NO FORCE ROW LEVEL SECURITY;
ALTER TABLE despesas_operacionais DISABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenancy_isolamento ON estoque_observacoes;
ALTER TABLE estoque_observacoes NO FORCE ROW LEVEL SECURITY;
ALTER TABLE estoque_observacoes DISABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenancy_isolamento ON ga4_performance_cache;
ALTER TABLE ga4_performance_cache NO FORCE ROW LEVEL SECURITY;
ALTER TABLE ga4_performance_cache DISABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenancy_isolamento ON google_analytics_connections;
ALTER TABLE google_analytics_connections NO FORCE ROW LEVEL SECURITY;
ALTER TABLE google_analytics_connections DISABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenancy_isolamento ON pedidos_backfill_jobs;
ALTER TABLE pedidos_backfill_jobs NO FORCE ROW LEVEL SECURITY;
ALTER TABLE pedidos_backfill_jobs DISABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenancy_isolamento ON pedidos_ink;
ALTER TABLE pedidos_ink NO FORCE ROW LEVEL SECURITY;
ALTER TABLE pedidos_ink DISABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenancy_isolamento ON pedidos_ink_itens;
ALTER TABLE pedidos_ink_itens NO FORCE ROW LEVEL SECURITY;
ALTER TABLE pedidos_ink_itens DISABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenancy_isolamento ON produtos_feed;
ALTER TABLE produtos_feed NO FORCE ROW LEVEL SECURITY;
ALTER TABLE produtos_feed DISABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenancy_isolamento ON produtos_feed_sync;
ALTER TABLE produtos_feed_sync NO FORCE ROW LEVEL SECURITY;
ALTER TABLE produtos_feed_sync DISABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenancy_isolamento ON produtos_ink;
ALTER TABLE produtos_ink NO FORCE ROW LEVEL SECURITY;
ALTER TABLE produtos_ink DISABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenancy_isolamento ON produtos_ink_sync;
ALTER TABLE produtos_ink_sync NO FORCE ROW LEVEL SECURITY;
ALTER TABLE produtos_ink_sync DISABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenancy_isolamento ON sync_estado;
ALTER TABLE sync_estado NO FORCE ROW LEVEL SECURITY;
ALTER TABLE sync_estado DISABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenancy_isolamento ON utm_campaigns;
ALTER TABLE utm_campaigns NO FORCE ROW LEVEL SECURITY;
ALTER TABLE utm_campaigns DISABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenancy_isolamento ON origens_migration_city_uf_map;
ALTER TABLE origens_migration_city_uf_map NO FORCE ROW LEVEL SECURITY;
ALTER TABLE origens_migration_city_uf_map DISABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenancy_isolamento ON origens_migration_rules;
ALTER TABLE origens_migration_rules NO FORCE ROW LEVEL SECURITY;
ALTER TABLE origens_migration_rules DISABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenancy_isolamento ON origens_migration_simulations;
ALTER TABLE origens_migration_simulations NO FORCE ROW LEVEL SECURITY;
ALTER TABLE origens_migration_simulations DISABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenancy_isolamento ON audit_log;
ALTER TABLE audit_log NO FORCE ROW LEVEL SECURITY;
ALTER TABLE audit_log DISABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenancy_isolamento ON media_assets;
ALTER TABLE media_assets NO FORCE ROW LEVEL SECURITY;
ALTER TABLE media_assets DISABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenancy_isolamento ON webhook_eventos;
ALTER TABLE webhook_eventos NO FORCE ROW LEVEL SECURITY;
ALTER TABLE webhook_eventos DISABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenancy_isolamento ON whatsapp_web_outbox;
ALTER TABLE whatsapp_web_outbox NO FORCE ROW LEVEL SECURITY;
ALTER TABLE whatsapp_web_outbox DISABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenancy_isolamento ON bulk_category_job_items;
ALTER TABLE bulk_category_job_items NO FORCE ROW LEVEL SECURITY;
ALTER TABLE bulk_category_job_items DISABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenancy_isolamento ON campaign_recipients;
ALTER TABLE campaign_recipients NO FORCE ROW LEVEL SECURITY;
ALTER TABLE campaign_recipients DISABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenancy_isolamento ON origens_migration_simulation_items;
ALTER TABLE origens_migration_simulation_items NO FORCE ROW LEVEL SECURITY;
ALTER TABLE origens_migration_simulation_items DISABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenancy_isolamento ON integration_secrets;
ALTER TABLE integration_secrets NO FORCE ROW LEVEL SECURITY;
ALTER TABLE integration_secrets DISABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenancy_isolamento ON integrations;
ALTER TABLE integrations NO FORCE ROW LEVEL SECURITY;
ALTER TABLE integrations DISABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenancy_isolamento ON app_config;
ALTER TABLE app_config NO FORCE ROW LEVEL SECURITY;
ALTER TABLE app_config DISABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenancy_isolamento ON custos_api_precos;
ALTER TABLE custos_api_precos NO FORCE ROW LEVEL SECURITY;
ALTER TABLE custos_api_precos DISABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenancy_isolamento ON segments;
ALTER TABLE segments NO FORCE ROW LEVEL SECURITY;
ALTER TABLE segments DISABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenancy_isolamento ON utm_presets;
ALTER TABLE utm_presets NO FORCE ROW LEVEL SECURITY;
ALTER TABLE utm_presets DISABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenancy_isolamento ON whatsapp_web_mensagens;
ALTER TABLE whatsapp_web_mensagens NO FORCE ROW LEVEL SECURITY;
ALTER TABLE whatsapp_web_mensagens DISABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenancy_isolamento ON meta_connections;
ALTER TABLE meta_connections NO FORCE ROW LEVEL SECURITY;
ALTER TABLE meta_connections DISABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenancy_isolamento ON meta_ad_accounts;
ALTER TABLE meta_ad_accounts NO FORCE ROW LEVEL SECURITY;
ALTER TABLE meta_ad_accounts DISABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenancy_isolamento ON meta_campaigns;
ALTER TABLE meta_campaigns NO FORCE ROW LEVEL SECURITY;
ALTER TABLE meta_campaigns DISABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenancy_isolamento ON meta_adsets;
ALTER TABLE meta_adsets NO FORCE ROW LEVEL SECURITY;
ALTER TABLE meta_adsets DISABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenancy_isolamento ON meta_ads;
ALTER TABLE meta_ads NO FORCE ROW LEVEL SECURITY;
ALTER TABLE meta_ads DISABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenancy_isolamento ON meta_creatives;
ALTER TABLE meta_creatives NO FORCE ROW LEVEL SECURITY;
ALTER TABLE meta_creatives DISABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenancy_isolamento ON meta_insights_daily;
ALTER TABLE meta_insights_daily NO FORCE ROW LEVEL SECURITY;
ALTER TABLE meta_insights_daily DISABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenancy_isolamento ON meta_sync_logs;
ALTER TABLE meta_sync_logs NO FORCE ROW LEVEL SECURITY;
ALTER TABLE meta_sync_logs DISABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenancy_isolamento ON google_ads_connections;
ALTER TABLE google_ads_connections NO FORCE ROW LEVEL SECURITY;
ALTER TABLE google_ads_connections DISABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenancy_isolamento ON google_ads_customers;
ALTER TABLE google_ads_customers NO FORCE ROW LEVEL SECURITY;
ALTER TABLE google_ads_customers DISABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenancy_isolamento ON google_ads_campaigns;
ALTER TABLE google_ads_campaigns NO FORCE ROW LEVEL SECURITY;
ALTER TABLE google_ads_campaigns DISABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenancy_isolamento ON google_ads_insights_daily;
ALTER TABLE google_ads_insights_daily NO FORCE ROW LEVEL SECURITY;
ALTER TABLE google_ads_insights_daily DISABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenancy_isolamento ON google_ads_sync_logs;
ALTER TABLE google_ads_sync_logs NO FORCE ROW LEVEL SECURITY;
ALTER TABLE google_ads_sync_logs DISABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenancy_isolamento ON creative_settings;
ALTER TABLE creative_settings NO FORCE ROW LEVEL SECURITY;
ALTER TABLE creative_settings DISABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenancy_isolamento ON creative_brand_profiles;
ALTER TABLE creative_brand_profiles NO FORCE ROW LEVEL SECURITY;
ALTER TABLE creative_brand_profiles DISABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenancy_isolamento ON creative_niche_profiles;
ALTER TABLE creative_niche_profiles NO FORCE ROW LEVEL SECURITY;
ALTER TABLE creative_niche_profiles DISABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenancy_isolamento ON creative_context_profiles;
ALTER TABLE creative_context_profiles NO FORCE ROW LEVEL SECURITY;
ALTER TABLE creative_context_profiles DISABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenancy_isolamento ON creative_personas;
ALTER TABLE creative_personas NO FORCE ROW LEVEL SECURITY;
ALTER TABLE creative_personas DISABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenancy_isolamento ON creative_products;
ALTER TABLE creative_products NO FORCE ROW LEVEL SECURITY;
ALTER TABLE creative_products DISABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenancy_isolamento ON creative_jobs;
ALTER TABLE creative_jobs NO FORCE ROW LEVEL SECURITY;
ALTER TABLE creative_jobs DISABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenancy_isolamento ON creative_generations;
ALTER TABLE creative_generations NO FORCE ROW LEVEL SECURITY;
ALTER TABLE creative_generations DISABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenancy_isolamento ON creative_assets;
ALTER TABLE creative_assets NO FORCE ROW LEVEL SECURITY;
ALTER TABLE creative_assets DISABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenancy_isolamento ON organizations;
ALTER TABLE organizations NO FORCE ROW LEVEL SECURITY;
ALTER TABLE organizations DISABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenancy_isolamento ON stores;
ALTER TABLE stores NO FORCE ROW LEVEL SECURITY;
ALTER TABLE stores DISABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenancy_isolamento ON organization_members;
ALTER TABLE organization_members NO FORCE ROW LEVEL SECURITY;
ALTER TABLE organization_members DISABLE ROW LEVEL SECURITY;
