-- Fase 1 · reverte o contract (recria as chaves globais)
-- GERADO por scripts/tenancy/gerar-sql-fase1.mjs a partir de lib/platform/tenancy-manifest.js.
-- Congelado: edite o manifesto e regenere só se o desenho mudar ANTES do primeiro deploy.

ALTER TABLE integration_secrets DROP CONSTRAINT integration_secrets_integration_id_org_fkey;
ALTER TABLE origens_migration_simulation_items DROP CONSTRAINT origens_migration_simulation_items_simulation_id_org_fkey;
ALTER TABLE campaign_recipients DROP CONSTRAINT campaign_recipients_campaign_id_org_fkey;
ALTER TABLE campaign_recipients DROP CONSTRAINT campaign_recipients_media_asset_id_org_fkey;
ALTER TABLE bulk_category_job_items DROP CONSTRAINT bulk_category_job_items_job_id_org_fkey;
ALTER TABLE whatsapp_web_outbox DROP CONSTRAINT whatsapp_web_outbox_campaign_recipient_id_org_fkey;
ALTER TABLE origens_migration_simulations DROP CONSTRAINT origens_migration_simulations_job_id_org_fkey;
ALTER TABLE campaigns DROP CONSTRAINT campaigns_segmento_id_org_fkey;
ALTER TABLE creative_assets DROP CONSTRAINT creative_assets_pkey;
DROP INDEX idx_creative_assets_pk_id;
ALTER TABLE creative_assets ADD CONSTRAINT creative_assets_pkey PRIMARY KEY (id);
ALTER TABLE creative_generations DROP CONSTRAINT creative_generations_pkey;
DROP INDEX idx_creative_generations_pk_creative_id;
ALTER TABLE creative_generations ADD CONSTRAINT creative_generations_pkey PRIMARY KEY (creative_id);
ALTER TABLE creative_jobs DROP CONSTRAINT creative_jobs_pkey;
DROP INDEX idx_creative_jobs_pk_id;
ALTER TABLE creative_jobs ADD CONSTRAINT creative_jobs_pkey PRIMARY KEY (id);
ALTER TABLE creative_products DROP CONSTRAINT creative_products_pkey;
DROP INDEX idx_creative_products_pk_id;
ALTER TABLE creative_products ADD CONSTRAINT creative_products_pkey PRIMARY KEY (id);
ALTER TABLE creative_personas DROP CONSTRAINT creative_personas_pkey;
DROP INDEX idx_creative_personas_pk_id;
ALTER TABLE creative_personas ADD CONSTRAINT creative_personas_pkey PRIMARY KEY (id);
ALTER TABLE creative_context_profiles DROP CONSTRAINT creative_context_profiles_pkey;
DROP INDEX idx_creative_context_profiles_pk_id;
ALTER TABLE creative_context_profiles ADD CONSTRAINT creative_context_profiles_pkey PRIMARY KEY (id);
ALTER TABLE creative_niche_profiles DROP CONSTRAINT creative_niche_profiles_pkey;
DROP INDEX idx_creative_niche_profiles_pk_id;
ALTER TABLE creative_niche_profiles ADD CONSTRAINT creative_niche_profiles_pkey PRIMARY KEY (id);
ALTER TABLE creative_brand_profiles DROP CONSTRAINT creative_brand_profiles_pkey;
DROP INDEX idx_creative_brand_profiles_pk_id;
ALTER TABLE creative_brand_profiles ADD CONSTRAINT creative_brand_profiles_pkey PRIMARY KEY (id);
ALTER TABLE creative_settings DROP CONSTRAINT uq_creative_settings_org;
CREATE UNIQUE INDEX uq_creative_settings_org ON creative_settings (organization_id);
ALTER TABLE creative_settings ADD CONSTRAINT creative_settings_pkey PRIMARY KEY (tenant_id);
ALTER TABLE google_ads_sync_logs DROP CONSTRAINT google_ads_sync_logs_pkey;
DROP INDEX idx_google_ads_sync_logs_pk_id;
ALTER TABLE google_ads_sync_logs ADD CONSTRAINT google_ads_sync_logs_pkey PRIMARY KEY (id);
ALTER TABLE google_ads_insights_daily DROP CONSTRAINT google_ads_insights_daily_pkey;
DROP INDEX idx_google_ads_insights_daily_pk_id;
ALTER TABLE google_ads_insights_daily ADD CONSTRAINT google_ads_insights_daily_pkey PRIMARY KEY (id);
ALTER TABLE google_ads_campaigns DROP CONSTRAINT google_ads_campaigns_pkey;
DROP INDEX idx_google_ads_campaigns_pk_id;
ALTER TABLE google_ads_campaigns ADD CONSTRAINT google_ads_campaigns_pkey PRIMARY KEY (id);
ALTER TABLE google_ads_customers DROP CONSTRAINT google_ads_customers_pkey;
DROP INDEX idx_google_ads_customers_pk_id;
ALTER TABLE google_ads_customers ADD CONSTRAINT google_ads_customers_pkey PRIMARY KEY (id);
ALTER TABLE google_ads_connections DROP CONSTRAINT google_ads_connections_pkey;
DROP INDEX idx_google_ads_connections_pk_id;
ALTER TABLE google_ads_connections ADD CONSTRAINT google_ads_connections_pkey PRIMARY KEY (id);
ALTER TABLE meta_sync_logs DROP CONSTRAINT meta_sync_logs_pkey;
DROP INDEX idx_meta_sync_logs_pk_id;
ALTER TABLE meta_sync_logs ADD CONSTRAINT meta_sync_logs_pkey PRIMARY KEY (id);
ALTER TABLE meta_insights_daily DROP CONSTRAINT meta_insights_daily_pkey;
DROP INDEX idx_meta_insights_daily_pk_id;
ALTER TABLE meta_insights_daily ADD CONSTRAINT meta_insights_daily_pkey PRIMARY KEY (id);
ALTER TABLE meta_creatives DROP CONSTRAINT meta_creatives_pkey;
DROP INDEX idx_meta_creatives_pk_id;
ALTER TABLE meta_creatives ADD CONSTRAINT meta_creatives_pkey PRIMARY KEY (id);
ALTER TABLE meta_ads DROP CONSTRAINT meta_ads_pkey;
DROP INDEX idx_meta_ads_pk_id;
ALTER TABLE meta_ads ADD CONSTRAINT meta_ads_pkey PRIMARY KEY (id);
ALTER TABLE meta_adsets DROP CONSTRAINT meta_adsets_pkey;
DROP INDEX idx_meta_adsets_pk_id;
ALTER TABLE meta_adsets ADD CONSTRAINT meta_adsets_pkey PRIMARY KEY (id);
ALTER TABLE meta_campaigns DROP CONSTRAINT meta_campaigns_pkey;
DROP INDEX idx_meta_campaigns_pk_id;
ALTER TABLE meta_campaigns ADD CONSTRAINT meta_campaigns_pkey PRIMARY KEY (id);
ALTER TABLE meta_ad_accounts DROP CONSTRAINT meta_ad_accounts_pkey;
DROP INDEX idx_meta_ad_accounts_pk_id;
ALTER TABLE meta_ad_accounts ADD CONSTRAINT meta_ad_accounts_pkey PRIMARY KEY (id);
ALTER TABLE meta_connections DROP CONSTRAINT meta_connections_pkey;
DROP INDEX idx_meta_connections_pk_id;
ALTER TABLE meta_connections ADD CONSTRAINT meta_connections_pkey PRIMARY KEY (id);
ALTER TABLE whatsapp_web_mensagens DROP CONSTRAINT whatsapp_web_mensagens_pkey;
DROP INDEX idx_whatsapp_web_mensagens_pk_id;
ALTER TABLE whatsapp_web_mensagens ADD CONSTRAINT whatsapp_web_mensagens_pkey PRIMARY KEY (id);
ALTER TABLE utm_presets DROP CONSTRAINT utm_presets_pkey;
DROP INDEX idx_utm_presets_pk_id;
ALTER TABLE utm_presets ADD CONSTRAINT utm_presets_pkey PRIMARY KEY (id);
ALTER TABLE segments DROP CONSTRAINT segments_pkey;
DROP INDEX idx_segments_pk_id;
ALTER TABLE segments ADD CONSTRAINT segments_pkey PRIMARY KEY (id);
ALTER TABLE custos_api_precos DROP CONSTRAINT uq_custos_api_precos_org;
CREATE UNIQUE INDEX uq_custos_api_precos_org ON custos_api_precos (organization_id, chave);
ALTER TABLE custos_api_precos ADD CONSTRAINT custos_api_precos_pkey PRIMARY KEY (chave);
ALTER TABLE app_config DROP CONSTRAINT uq_app_config_org;
CREATE UNIQUE INDEX uq_app_config_org ON app_config (organization_id, chave);
ALTER TABLE app_config ADD CONSTRAINT app_config_pkey PRIMARY KEY (chave);
ALTER TABLE integrations DROP CONSTRAINT integrations_pkey;
DROP INDEX idx_integrations_pk_id;
ALTER TABLE integrations ADD CONSTRAINT integrations_pkey PRIMARY KEY (id);
ALTER TABLE integration_secrets DROP CONSTRAINT integration_secrets_pkey;
DROP INDEX idx_integration_secrets_pk_id;
ALTER TABLE integration_secrets ADD CONSTRAINT integration_secrets_pkey PRIMARY KEY (id);
ALTER TABLE origens_migration_simulation_items DROP CONSTRAINT origens_migration_simulation_items_pkey;
DROP INDEX idx_origens_migration_simulation_items_pk_id;
ALTER TABLE origens_migration_simulation_items ADD CONSTRAINT origens_migration_simulation_items_pkey PRIMARY KEY (id);
ALTER TABLE campaign_recipients DROP CONSTRAINT campaign_recipients_pkey;
DROP INDEX idx_campaign_recipients_pk_id;
ALTER TABLE campaign_recipients ADD CONSTRAINT campaign_recipients_pkey PRIMARY KEY (id);
ALTER TABLE bulk_category_job_items DROP CONSTRAINT bulk_category_job_items_pkey;
DROP INDEX idx_bulk_category_job_items_pk_id;
ALTER TABLE bulk_category_job_items ADD CONSTRAINT bulk_category_job_items_pkey PRIMARY KEY (id);
ALTER TABLE whatsapp_web_outbox DROP CONSTRAINT whatsapp_web_outbox_pkey;
DROP INDEX idx_whatsapp_web_outbox_pk_id;
ALTER TABLE whatsapp_web_outbox ADD CONSTRAINT whatsapp_web_outbox_pkey PRIMARY KEY (id);
ALTER TABLE webhook_eventos DROP CONSTRAINT webhook_eventos_pkey;
DROP INDEX idx_webhook_eventos_pk_id;
ALTER TABLE webhook_eventos ADD CONSTRAINT webhook_eventos_pkey PRIMARY KEY (id);
DROP INDEX idx_media_assets_public_token_busca;
ALTER TABLE media_assets DROP CONSTRAINT media_assets_pkey;
DROP INDEX idx_media_assets_pk_id;
ALTER TABLE media_assets ADD CONSTRAINT media_assets_pkey PRIMARY KEY (id);
ALTER TABLE audit_log DROP CONSTRAINT audit_log_pkey;
DROP INDEX idx_audit_log_pk_id;
ALTER TABLE audit_log ADD CONSTRAINT audit_log_pkey PRIMARY KEY (id);
ALTER TABLE origens_migration_simulations DROP CONSTRAINT origens_migration_simulations_pkey;
DROP INDEX idx_origens_migration_simulations_pk_id;
ALTER TABLE origens_migration_simulations ADD CONSTRAINT origens_migration_simulations_pkey PRIMARY KEY (id);
ALTER TABLE origens_migration_rules DROP CONSTRAINT origens_migration_rules_pkey;
DROP INDEX idx_origens_migration_rules_pk_id;
ALTER TABLE origens_migration_rules ADD CONSTRAINT origens_migration_rules_pkey PRIMARY KEY (id);
ALTER TABLE origens_migration_city_uf_map DROP CONSTRAINT origens_migration_city_uf_map_pkey;
DROP INDEX idx_origens_migration_city_uf_map_pk_id;
ALTER TABLE origens_migration_city_uf_map ADD CONSTRAINT origens_migration_city_uf_map_pkey PRIMARY KEY (id);
ALTER TABLE utm_campaigns DROP CONSTRAINT utm_campaigns_pkey;
DROP INDEX idx_utm_campaigns_pk_id;
ALTER TABLE utm_campaigns ADD CONSTRAINT utm_campaigns_pkey PRIMARY KEY (id);
ALTER TABLE sync_estado DROP CONSTRAINT uq_sync_estado_org;
CREATE UNIQUE INDEX uq_sync_estado_org ON sync_estado (organization_id, loja);
ALTER TABLE sync_estado ADD CONSTRAINT sync_estado_pkey PRIMARY KEY (loja);
ALTER TABLE produtos_ink_sync DROP CONSTRAINT uq_produtos_ink_sync_org;
CREATE UNIQUE INDEX uq_produtos_ink_sync_org ON produtos_ink_sync (organization_id, loja);
ALTER TABLE produtos_ink_sync ADD CONSTRAINT produtos_ink_sync_pkey PRIMARY KEY (loja);
ALTER TABLE produtos_ink DROP CONSTRAINT uq_produtos_ink_org;
CREATE UNIQUE INDEX uq_produtos_ink_org ON produtos_ink (organization_id, loja, produto_id);
ALTER TABLE produtos_ink ADD CONSTRAINT produtos_ink_pkey PRIMARY KEY (loja, produto_id);
ALTER TABLE produtos_feed_sync DROP CONSTRAINT uq_produtos_feed_sync_org;
CREATE UNIQUE INDEX uq_produtos_feed_sync_org ON produtos_feed_sync (organization_id, loja);
ALTER TABLE produtos_feed_sync ADD CONSTRAINT produtos_feed_sync_pkey PRIMARY KEY (loja);
ALTER TABLE produtos_feed DROP CONSTRAINT uq_produtos_feed_org;
CREATE UNIQUE INDEX uq_produtos_feed_org ON produtos_feed (organization_id, loja, produto_id);
ALTER TABLE produtos_feed ADD CONSTRAINT produtos_feed_pkey PRIMARY KEY (loja, produto_id);
ALTER TABLE pedidos_ink_itens DROP CONSTRAINT uq_pedidos_ink_itens_org;
CREATE UNIQUE INDEX uq_pedidos_ink_itens_org ON pedidos_ink_itens (organization_id, loja, item_id);
ALTER TABLE pedidos_ink_itens ADD CONSTRAINT pedidos_ink_itens_pkey PRIMARY KEY (loja, item_id);
ALTER TABLE pedidos_ink DROP CONSTRAINT pedidos_ink_pkey;
DROP INDEX idx_pedidos_ink_pk_id;
ALTER TABLE pedidos_ink ADD CONSTRAINT pedidos_ink_pkey PRIMARY KEY (id);
ALTER TABLE pedidos_backfill_jobs DROP CONSTRAINT pedidos_backfill_jobs_pkey;
DROP INDEX idx_pedidos_backfill_jobs_pk_id;
ALTER TABLE pedidos_backfill_jobs ADD CONSTRAINT pedidos_backfill_jobs_pkey PRIMARY KEY (id);
ALTER TABLE google_analytics_connections DROP CONSTRAINT google_analytics_connections_pkey;
DROP INDEX idx_google_analytics_connections_pk_id;
ALTER TABLE google_analytics_connections ADD CONSTRAINT google_analytics_connections_pkey PRIMARY KEY (id);
ALTER TABLE ga4_performance_cache DROP CONSTRAINT ga4_performance_cache_pkey;
DROP INDEX idx_ga4_performance_cache_pk_id;
ALTER TABLE ga4_performance_cache ADD CONSTRAINT ga4_performance_cache_pkey PRIMARY KEY (id);
ALTER TABLE estoque_observacoes DROP CONSTRAINT estoque_observacoes_pkey;
DROP INDEX idx_estoque_observacoes_pk_id;
ALTER TABLE estoque_observacoes ADD CONSTRAINT estoque_observacoes_pkey PRIMARY KEY (id);
ALTER TABLE despesas_operacionais DROP CONSTRAINT despesas_operacionais_pkey;
DROP INDEX idx_despesas_operacionais_pk_id;
ALTER TABLE despesas_operacionais ADD CONSTRAINT despesas_operacionais_pkey PRIMARY KEY (id);
ALTER TABLE controle_estoque_observacoes DROP CONSTRAINT controle_estoque_observacoes_pkey;
DROP INDEX idx_controle_estoque_observacoes_pk_id;
ALTER TABLE controle_estoque_observacoes ADD CONSTRAINT controle_estoque_observacoes_pkey PRIMARY KEY (id);
ALTER TABLE campaigns DROP CONSTRAINT campaigns_pkey;
DROP INDEX idx_campaigns_pk_id;
ALTER TABLE campaigns ADD CONSTRAINT campaigns_pkey PRIMARY KEY (id);
ALTER TABLE bulk_category_jobs DROP CONSTRAINT bulk_category_jobs_pkey;
DROP INDEX idx_bulk_category_jobs_pk_id;
ALTER TABLE bulk_category_jobs ADD CONSTRAINT bulk_category_jobs_pkey PRIMARY KEY (id);
ALTER TABLE ga4_performance_cache ADD CONSTRAINT ga4_performance_cache_loja_periodo_key UNIQUE (loja, periodo);
ALTER TABLE google_analytics_connections ADD CONSTRAINT google_analytics_connections_loja_key UNIQUE (loja);
ALTER TABLE pedidos_ink ADD CONSTRAINT pedidos_ink_loja_ink_order_id_key UNIQUE (loja, ink_order_id);
ALTER TABLE origens_migration_city_uf_map ADD CONSTRAINT origens_migration_city_uf_map_loja_cidade_normalizada_key UNIQUE (loja, cidade_normalizada);
CREATE UNIQUE INDEX uq_wa_web_outbox_dedupe ON whatsapp_web_outbox USING btree (dedupe_key) WHERE (status = ANY (ARRAY['aguardando_aprovacao'::text, 'pending'::text, 'claimed'::text, 'sent'::text, 'desconhecido'::text]));
ALTER TABLE campaign_recipients ADD CONSTRAINT campaign_recipients_campaign_id_customer_key_key UNIQUE (campaign_id, customer_key);
CREATE UNIQUE INDEX idx_integration_secrets_integracao_tipo ON integration_secrets USING btree (integration_id, tipo);
CREATE UNIQUE INDEX uq_wa_web_mensagens_nome ON whatsapp_web_mensagens USING btree (lower(nome));
ALTER TABLE meta_ad_accounts ADD CONSTRAINT meta_ad_accounts_meta_account_id_key UNIQUE (meta_account_id);
CREATE UNIQUE INDEX uq_meta_ad_accounts_selecionada ON meta_ad_accounts USING btree (selecionada) WHERE selecionada;
ALTER TABLE meta_campaigns ADD CONSTRAINT meta_campaigns_meta_campaign_id_key UNIQUE (meta_campaign_id);
ALTER TABLE meta_adsets ADD CONSTRAINT meta_adsets_meta_adset_id_key UNIQUE (meta_adset_id);
ALTER TABLE meta_ads ADD CONSTRAINT meta_ads_meta_ad_id_key UNIQUE (meta_ad_id);
ALTER TABLE meta_creatives ADD CONSTRAINT meta_creatives_meta_creative_id_key UNIQUE (meta_creative_id);
ALTER TABLE meta_insights_daily ADD CONSTRAINT meta_insights_daily_meta_account_id_level_entidade_id_data__key UNIQUE (meta_account_id, level, entidade_id, data, attribution_setting);
ALTER TABLE google_ads_customers ADD CONSTRAINT google_ads_customers_customer_id_key UNIQUE (customer_id);
CREATE UNIQUE INDEX uq_google_ads_customers_selecionada ON google_ads_customers USING btree (selecionada) WHERE selecionada;
ALTER TABLE google_ads_campaigns ADD CONSTRAINT google_ads_campaigns_customer_id_campaign_id_key UNIQUE (customer_id, campaign_id);
ALTER TABLE google_ads_insights_daily ADD CONSTRAINT google_ads_insights_daily_customer_id_level_entidade_id_dat_key UNIQUE (customer_id, level, entidade_id, data, contagem_conversao);
CREATE UNIQUE INDEX idx_media_assets_public_token ON media_assets USING btree (public_token) WHERE (public_token IS NOT NULL);
ALTER TABLE bulk_category_job_items ADD CONSTRAINT bulk_category_job_items_job_id_fkey FOREIGN KEY (job_id) REFERENCES bulk_category_jobs(id) ON DELETE CASCADE;
ALTER TABLE campaign_recipients ADD CONSTRAINT campaign_recipients_campaign_id_fkey FOREIGN KEY (campaign_id) REFERENCES campaigns(id) ON DELETE CASCADE;
ALTER TABLE campaign_recipients ADD CONSTRAINT campaign_recipients_media_asset_id_fkey FOREIGN KEY (media_asset_id) REFERENCES media_assets(id) ON DELETE SET NULL;
ALTER TABLE campaigns ADD CONSTRAINT campaigns_segmento_id_fkey FOREIGN KEY (segmento_id) REFERENCES segments(id) ON DELETE SET NULL;
ALTER TABLE integration_secrets ADD CONSTRAINT integration_secrets_integration_id_fkey FOREIGN KEY (integration_id) REFERENCES integrations(id) ON DELETE CASCADE;
ALTER TABLE origens_migration_simulation_items ADD CONSTRAINT origens_migration_simulation_items_simulation_id_fkey FOREIGN KEY (simulation_id) REFERENCES origens_migration_simulations(id) ON DELETE CASCADE;
ALTER TABLE origens_migration_simulations ADD CONSTRAINT origens_migration_simulations_job_id_fkey FOREIGN KEY (job_id) REFERENCES bulk_category_jobs(id) ON DELETE SET NULL;
ALTER TABLE whatsapp_web_outbox ADD CONSTRAINT whatsapp_web_outbox_campaign_recipient_id_fkey FOREIGN KEY (campaign_recipient_id) REFERENCES campaign_recipients(id) ON DELETE CASCADE;
