-- Fase 1 · contract — toda chave de tabela tenant-owned inclui organization_id
-- GERADO por scripts/tenancy/gerar-sql-fase1.mjs a partir de lib/platform/tenancy-manifest.js.
-- Congelado: edite o manifesto e regenere só se o desenho mudar ANTES do primeiro deploy.

-- Deploy em DOIS passos (OPS-17): esta migration só pode rodar quando a versão no ar já usa os
-- alvos de ON CONFLICT com organization_id. A versão anterior à Fase 1 usa os alvos globais que
-- este arquivo remove.
-- 1. FKs antigas (referenciam PKs de uma coluna só).
ALTER TABLE bulk_category_job_items DROP CONSTRAINT bulk_category_job_items_job_id_fkey;
ALTER TABLE campaign_recipients DROP CONSTRAINT campaign_recipients_campaign_id_fkey;
ALTER TABLE campaign_recipients DROP CONSTRAINT campaign_recipients_media_asset_id_fkey;
ALTER TABLE campaigns DROP CONSTRAINT campaigns_segmento_id_fkey;
ALTER TABLE integration_secrets DROP CONSTRAINT integration_secrets_integration_id_fkey;
ALTER TABLE origens_migration_simulation_items DROP CONSTRAINT origens_migration_simulation_items_simulation_id_fkey;
ALTER TABLE origens_migration_simulations DROP CONSTRAINT origens_migration_simulations_job_id_fkey;
ALTER TABLE whatsapp_web_outbox DROP CONSTRAINT whatsapp_web_outbox_campaign_recipient_id_fkey;

-- 2. UNIQUEs globais que ainda restavam (os alvos de ON CONFLICT já incluem organization_id).
ALTER TABLE ga4_performance_cache DROP CONSTRAINT ga4_performance_cache_loja_periodo_key;
ALTER TABLE google_analytics_connections DROP CONSTRAINT google_analytics_connections_loja_key;
ALTER TABLE pedidos_ink DROP CONSTRAINT pedidos_ink_loja_ink_order_id_key;
ALTER TABLE origens_migration_city_uf_map DROP CONSTRAINT origens_migration_city_uf_map_loja_cidade_normalizada_key;
DROP INDEX uq_wa_web_outbox_dedupe;
ALTER TABLE campaign_recipients DROP CONSTRAINT campaign_recipients_campaign_id_customer_key_key;
DROP INDEX idx_integration_secrets_integracao_tipo;
DROP INDEX uq_wa_web_mensagens_nome;
ALTER TABLE meta_ad_accounts DROP CONSTRAINT meta_ad_accounts_meta_account_id_key;
DROP INDEX uq_meta_ad_accounts_selecionada;
ALTER TABLE meta_campaigns DROP CONSTRAINT meta_campaigns_meta_campaign_id_key;
ALTER TABLE meta_adsets DROP CONSTRAINT meta_adsets_meta_adset_id_key;
ALTER TABLE meta_ads DROP CONSTRAINT meta_ads_meta_ad_id_key;
ALTER TABLE meta_creatives DROP CONSTRAINT meta_creatives_meta_creative_id_key;
ALTER TABLE meta_insights_daily DROP CONSTRAINT meta_insights_daily_meta_account_id_level_entidade_id_data__key;
ALTER TABLE google_ads_customers DROP CONSTRAINT google_ads_customers_customer_id_key;
DROP INDEX uq_google_ads_customers_selecionada;
ALTER TABLE google_ads_campaigns DROP CONSTRAINT google_ads_campaigns_customer_id_campaign_id_key;
ALTER TABLE google_ads_insights_daily DROP CONSTRAINT google_ads_insights_daily_customer_id_level_entidade_id_dat_key;
DROP INDEX idx_media_assets_public_token;

-- 3. PKs passam a começar por organization_id.
ALTER TABLE bulk_category_jobs DROP CONSTRAINT bulk_category_jobs_pkey;
ALTER TABLE bulk_category_jobs ADD CONSTRAINT bulk_category_jobs_pkey PRIMARY KEY (organization_id, id);
CREATE INDEX idx_bulk_category_jobs_pk_id ON bulk_category_jobs (id);
ALTER TABLE campaigns DROP CONSTRAINT campaigns_pkey;
ALTER TABLE campaigns ADD CONSTRAINT campaigns_pkey PRIMARY KEY (organization_id, id);
CREATE INDEX idx_campaigns_pk_id ON campaigns (id);
ALTER TABLE controle_estoque_observacoes DROP CONSTRAINT controle_estoque_observacoes_pkey;
ALTER TABLE controle_estoque_observacoes ADD CONSTRAINT controle_estoque_observacoes_pkey PRIMARY KEY (organization_id, id);
CREATE INDEX idx_controle_estoque_observacoes_pk_id ON controle_estoque_observacoes (id);
ALTER TABLE despesas_operacionais DROP CONSTRAINT despesas_operacionais_pkey;
ALTER TABLE despesas_operacionais ADD CONSTRAINT despesas_operacionais_pkey PRIMARY KEY (organization_id, id);
CREATE INDEX idx_despesas_operacionais_pk_id ON despesas_operacionais (id);
ALTER TABLE estoque_observacoes DROP CONSTRAINT estoque_observacoes_pkey;
ALTER TABLE estoque_observacoes ADD CONSTRAINT estoque_observacoes_pkey PRIMARY KEY (organization_id, id);
CREATE INDEX idx_estoque_observacoes_pk_id ON estoque_observacoes (id);
ALTER TABLE ga4_performance_cache DROP CONSTRAINT ga4_performance_cache_pkey;
ALTER TABLE ga4_performance_cache ADD CONSTRAINT ga4_performance_cache_pkey PRIMARY KEY (organization_id, id);
CREATE INDEX idx_ga4_performance_cache_pk_id ON ga4_performance_cache (id);
ALTER TABLE google_analytics_connections DROP CONSTRAINT google_analytics_connections_pkey;
ALTER TABLE google_analytics_connections ADD CONSTRAINT google_analytics_connections_pkey PRIMARY KEY (organization_id, id);
CREATE INDEX idx_google_analytics_connections_pk_id ON google_analytics_connections (id);
ALTER TABLE pedidos_backfill_jobs DROP CONSTRAINT pedidos_backfill_jobs_pkey;
ALTER TABLE pedidos_backfill_jobs ADD CONSTRAINT pedidos_backfill_jobs_pkey PRIMARY KEY (organization_id, id);
CREATE INDEX idx_pedidos_backfill_jobs_pk_id ON pedidos_backfill_jobs (id);
ALTER TABLE pedidos_ink DROP CONSTRAINT pedidos_ink_pkey;
ALTER TABLE pedidos_ink ADD CONSTRAINT pedidos_ink_pkey PRIMARY KEY (organization_id, id);
CREATE INDEX idx_pedidos_ink_pk_id ON pedidos_ink (id);
ALTER TABLE pedidos_ink_itens DROP CONSTRAINT pedidos_ink_itens_pkey;
ALTER TABLE pedidos_ink_itens ADD CONSTRAINT uq_pedidos_ink_itens_org PRIMARY KEY USING INDEX uq_pedidos_ink_itens_org;
ALTER TABLE produtos_feed DROP CONSTRAINT produtos_feed_pkey;
ALTER TABLE produtos_feed ADD CONSTRAINT uq_produtos_feed_org PRIMARY KEY USING INDEX uq_produtos_feed_org;
ALTER TABLE produtos_feed_sync DROP CONSTRAINT produtos_feed_sync_pkey;
ALTER TABLE produtos_feed_sync ADD CONSTRAINT uq_produtos_feed_sync_org PRIMARY KEY USING INDEX uq_produtos_feed_sync_org;
ALTER TABLE produtos_ink DROP CONSTRAINT produtos_ink_pkey;
ALTER TABLE produtos_ink ADD CONSTRAINT uq_produtos_ink_org PRIMARY KEY USING INDEX uq_produtos_ink_org;
ALTER TABLE produtos_ink_sync DROP CONSTRAINT produtos_ink_sync_pkey;
ALTER TABLE produtos_ink_sync ADD CONSTRAINT uq_produtos_ink_sync_org PRIMARY KEY USING INDEX uq_produtos_ink_sync_org;
ALTER TABLE sync_estado DROP CONSTRAINT sync_estado_pkey;
ALTER TABLE sync_estado ADD CONSTRAINT uq_sync_estado_org PRIMARY KEY USING INDEX uq_sync_estado_org;
ALTER TABLE utm_campaigns DROP CONSTRAINT utm_campaigns_pkey;
ALTER TABLE utm_campaigns ADD CONSTRAINT utm_campaigns_pkey PRIMARY KEY (organization_id, id);
CREATE INDEX idx_utm_campaigns_pk_id ON utm_campaigns (id);
ALTER TABLE origens_migration_city_uf_map DROP CONSTRAINT origens_migration_city_uf_map_pkey;
ALTER TABLE origens_migration_city_uf_map ADD CONSTRAINT origens_migration_city_uf_map_pkey PRIMARY KEY (organization_id, id);
CREATE INDEX idx_origens_migration_city_uf_map_pk_id ON origens_migration_city_uf_map (id);
ALTER TABLE origens_migration_rules DROP CONSTRAINT origens_migration_rules_pkey;
ALTER TABLE origens_migration_rules ADD CONSTRAINT origens_migration_rules_pkey PRIMARY KEY (organization_id, id);
CREATE INDEX idx_origens_migration_rules_pk_id ON origens_migration_rules (id);
ALTER TABLE origens_migration_simulations DROP CONSTRAINT origens_migration_simulations_pkey;
ALTER TABLE origens_migration_simulations ADD CONSTRAINT origens_migration_simulations_pkey PRIMARY KEY (organization_id, id);
CREATE INDEX idx_origens_migration_simulations_pk_id ON origens_migration_simulations (id);
ALTER TABLE audit_log DROP CONSTRAINT audit_log_pkey;
ALTER TABLE audit_log ADD CONSTRAINT audit_log_pkey PRIMARY KEY (organization_id, id);
CREATE INDEX idx_audit_log_pk_id ON audit_log (id);
ALTER TABLE media_assets DROP CONSTRAINT media_assets_pkey;
ALTER TABLE media_assets ADD CONSTRAINT media_assets_pkey PRIMARY KEY (organization_id, id);
CREATE INDEX idx_media_assets_pk_id ON media_assets (id);
CREATE INDEX idx_media_assets_public_token_busca ON media_assets (public_token);
ALTER TABLE webhook_eventos DROP CONSTRAINT webhook_eventos_pkey;
ALTER TABLE webhook_eventos ADD CONSTRAINT webhook_eventos_pkey PRIMARY KEY (organization_id, id);
CREATE INDEX idx_webhook_eventos_pk_id ON webhook_eventos (id);
ALTER TABLE whatsapp_web_outbox DROP CONSTRAINT whatsapp_web_outbox_pkey;
ALTER TABLE whatsapp_web_outbox ADD CONSTRAINT whatsapp_web_outbox_pkey PRIMARY KEY (organization_id, id);
CREATE INDEX idx_whatsapp_web_outbox_pk_id ON whatsapp_web_outbox (id);
ALTER TABLE bulk_category_job_items DROP CONSTRAINT bulk_category_job_items_pkey;
ALTER TABLE bulk_category_job_items ADD CONSTRAINT bulk_category_job_items_pkey PRIMARY KEY (organization_id, id);
CREATE INDEX idx_bulk_category_job_items_pk_id ON bulk_category_job_items (id);
ALTER TABLE campaign_recipients DROP CONSTRAINT campaign_recipients_pkey;
ALTER TABLE campaign_recipients ADD CONSTRAINT campaign_recipients_pkey PRIMARY KEY (organization_id, id);
CREATE INDEX idx_campaign_recipients_pk_id ON campaign_recipients (id);
ALTER TABLE origens_migration_simulation_items DROP CONSTRAINT origens_migration_simulation_items_pkey;
ALTER TABLE origens_migration_simulation_items ADD CONSTRAINT origens_migration_simulation_items_pkey PRIMARY KEY (organization_id, id);
CREATE INDEX idx_origens_migration_simulation_items_pk_id ON origens_migration_simulation_items (id);
ALTER TABLE integration_secrets DROP CONSTRAINT integration_secrets_pkey;
ALTER TABLE integration_secrets ADD CONSTRAINT integration_secrets_pkey PRIMARY KEY (organization_id, id);
CREATE INDEX idx_integration_secrets_pk_id ON integration_secrets (id);
ALTER TABLE integrations DROP CONSTRAINT integrations_pkey;
ALTER TABLE integrations ADD CONSTRAINT integrations_pkey PRIMARY KEY (organization_id, id);
CREATE INDEX idx_integrations_pk_id ON integrations (id);
ALTER TABLE app_config DROP CONSTRAINT app_config_pkey;
ALTER TABLE app_config ADD CONSTRAINT uq_app_config_org PRIMARY KEY USING INDEX uq_app_config_org;
ALTER TABLE custos_api_precos DROP CONSTRAINT custos_api_precos_pkey;
ALTER TABLE custos_api_precos ADD CONSTRAINT uq_custos_api_precos_org PRIMARY KEY USING INDEX uq_custos_api_precos_org;
ALTER TABLE segments DROP CONSTRAINT segments_pkey;
ALTER TABLE segments ADD CONSTRAINT segments_pkey PRIMARY KEY (organization_id, id);
CREATE INDEX idx_segments_pk_id ON segments (id);
ALTER TABLE utm_presets DROP CONSTRAINT utm_presets_pkey;
ALTER TABLE utm_presets ADD CONSTRAINT utm_presets_pkey PRIMARY KEY (organization_id, id);
CREATE INDEX idx_utm_presets_pk_id ON utm_presets (id);
ALTER TABLE whatsapp_web_mensagens DROP CONSTRAINT whatsapp_web_mensagens_pkey;
ALTER TABLE whatsapp_web_mensagens ADD CONSTRAINT whatsapp_web_mensagens_pkey PRIMARY KEY (organization_id, id);
CREATE INDEX idx_whatsapp_web_mensagens_pk_id ON whatsapp_web_mensagens (id);
ALTER TABLE meta_connections DROP CONSTRAINT meta_connections_pkey;
ALTER TABLE meta_connections ADD CONSTRAINT meta_connections_pkey PRIMARY KEY (organization_id, id);
CREATE INDEX idx_meta_connections_pk_id ON meta_connections (id);
ALTER TABLE meta_ad_accounts DROP CONSTRAINT meta_ad_accounts_pkey;
ALTER TABLE meta_ad_accounts ADD CONSTRAINT meta_ad_accounts_pkey PRIMARY KEY (organization_id, id);
CREATE INDEX idx_meta_ad_accounts_pk_id ON meta_ad_accounts (id);
ALTER TABLE meta_campaigns DROP CONSTRAINT meta_campaigns_pkey;
ALTER TABLE meta_campaigns ADD CONSTRAINT meta_campaigns_pkey PRIMARY KEY (organization_id, id);
CREATE INDEX idx_meta_campaigns_pk_id ON meta_campaigns (id);
ALTER TABLE meta_adsets DROP CONSTRAINT meta_adsets_pkey;
ALTER TABLE meta_adsets ADD CONSTRAINT meta_adsets_pkey PRIMARY KEY (organization_id, id);
CREATE INDEX idx_meta_adsets_pk_id ON meta_adsets (id);
ALTER TABLE meta_ads DROP CONSTRAINT meta_ads_pkey;
ALTER TABLE meta_ads ADD CONSTRAINT meta_ads_pkey PRIMARY KEY (organization_id, id);
CREATE INDEX idx_meta_ads_pk_id ON meta_ads (id);
ALTER TABLE meta_creatives DROP CONSTRAINT meta_creatives_pkey;
ALTER TABLE meta_creatives ADD CONSTRAINT meta_creatives_pkey PRIMARY KEY (organization_id, id);
CREATE INDEX idx_meta_creatives_pk_id ON meta_creatives (id);
ALTER TABLE meta_insights_daily DROP CONSTRAINT meta_insights_daily_pkey;
ALTER TABLE meta_insights_daily ADD CONSTRAINT meta_insights_daily_pkey PRIMARY KEY (organization_id, id);
CREATE INDEX idx_meta_insights_daily_pk_id ON meta_insights_daily (id);
ALTER TABLE meta_sync_logs DROP CONSTRAINT meta_sync_logs_pkey;
ALTER TABLE meta_sync_logs ADD CONSTRAINT meta_sync_logs_pkey PRIMARY KEY (organization_id, id);
CREATE INDEX idx_meta_sync_logs_pk_id ON meta_sync_logs (id);
ALTER TABLE google_ads_connections DROP CONSTRAINT google_ads_connections_pkey;
ALTER TABLE google_ads_connections ADD CONSTRAINT google_ads_connections_pkey PRIMARY KEY (organization_id, id);
CREATE INDEX idx_google_ads_connections_pk_id ON google_ads_connections (id);
ALTER TABLE google_ads_customers DROP CONSTRAINT google_ads_customers_pkey;
ALTER TABLE google_ads_customers ADD CONSTRAINT google_ads_customers_pkey PRIMARY KEY (organization_id, id);
CREATE INDEX idx_google_ads_customers_pk_id ON google_ads_customers (id);
ALTER TABLE google_ads_campaigns DROP CONSTRAINT google_ads_campaigns_pkey;
ALTER TABLE google_ads_campaigns ADD CONSTRAINT google_ads_campaigns_pkey PRIMARY KEY (organization_id, id);
CREATE INDEX idx_google_ads_campaigns_pk_id ON google_ads_campaigns (id);
ALTER TABLE google_ads_insights_daily DROP CONSTRAINT google_ads_insights_daily_pkey;
ALTER TABLE google_ads_insights_daily ADD CONSTRAINT google_ads_insights_daily_pkey PRIMARY KEY (organization_id, id);
CREATE INDEX idx_google_ads_insights_daily_pk_id ON google_ads_insights_daily (id);
ALTER TABLE google_ads_sync_logs DROP CONSTRAINT google_ads_sync_logs_pkey;
ALTER TABLE google_ads_sync_logs ADD CONSTRAINT google_ads_sync_logs_pkey PRIMARY KEY (organization_id, id);
CREATE INDEX idx_google_ads_sync_logs_pk_id ON google_ads_sync_logs (id);
ALTER TABLE creative_settings DROP CONSTRAINT creative_settings_pkey;
ALTER TABLE creative_settings ADD CONSTRAINT uq_creative_settings_org PRIMARY KEY USING INDEX uq_creative_settings_org;
ALTER TABLE creative_brand_profiles DROP CONSTRAINT creative_brand_profiles_pkey;
ALTER TABLE creative_brand_profiles ADD CONSTRAINT creative_brand_profiles_pkey PRIMARY KEY (organization_id, id);
CREATE INDEX idx_creative_brand_profiles_pk_id ON creative_brand_profiles (id);
ALTER TABLE creative_niche_profiles DROP CONSTRAINT creative_niche_profiles_pkey;
ALTER TABLE creative_niche_profiles ADD CONSTRAINT creative_niche_profiles_pkey PRIMARY KEY (organization_id, id);
CREATE INDEX idx_creative_niche_profiles_pk_id ON creative_niche_profiles (id);
ALTER TABLE creative_context_profiles DROP CONSTRAINT creative_context_profiles_pkey;
ALTER TABLE creative_context_profiles ADD CONSTRAINT creative_context_profiles_pkey PRIMARY KEY (organization_id, id);
CREATE INDEX idx_creative_context_profiles_pk_id ON creative_context_profiles (id);
ALTER TABLE creative_personas DROP CONSTRAINT creative_personas_pkey;
ALTER TABLE creative_personas ADD CONSTRAINT creative_personas_pkey PRIMARY KEY (organization_id, id);
CREATE INDEX idx_creative_personas_pk_id ON creative_personas (id);
ALTER TABLE creative_products DROP CONSTRAINT creative_products_pkey;
ALTER TABLE creative_products ADD CONSTRAINT creative_products_pkey PRIMARY KEY (organization_id, id);
CREATE INDEX idx_creative_products_pk_id ON creative_products (id);
ALTER TABLE creative_jobs DROP CONSTRAINT creative_jobs_pkey;
ALTER TABLE creative_jobs ADD CONSTRAINT creative_jobs_pkey PRIMARY KEY (organization_id, id);
CREATE INDEX idx_creative_jobs_pk_id ON creative_jobs (id);
ALTER TABLE creative_generations DROP CONSTRAINT creative_generations_pkey;
ALTER TABLE creative_generations ADD CONSTRAINT creative_generations_pkey PRIMARY KEY (organization_id, creative_id);
CREATE INDEX idx_creative_generations_pk_creative_id ON creative_generations (creative_id);
ALTER TABLE creative_assets DROP CONSTRAINT creative_assets_pkey;
ALTER TABLE creative_assets ADD CONSTRAINT creative_assets_pkey PRIMARY KEY (organization_id, id);
CREATE INDEX idx_creative_assets_pk_id ON creative_assets (id);

-- 4. FKs compostas: o filho só aponta para pai da MESMA Organization.
ALTER TABLE campaigns ADD CONSTRAINT campaigns_segmento_id_org_fkey FOREIGN KEY (organization_id, segmento_id) REFERENCES segments (organization_id, id) ON DELETE SET NULL (segmento_id);
ALTER TABLE origens_migration_simulations ADD CONSTRAINT origens_migration_simulations_job_id_org_fkey FOREIGN KEY (organization_id, job_id) REFERENCES bulk_category_jobs (organization_id, id) ON DELETE SET NULL (job_id);
ALTER TABLE whatsapp_web_outbox ADD CONSTRAINT whatsapp_web_outbox_campaign_recipient_id_org_fkey FOREIGN KEY (organization_id, campaign_recipient_id) REFERENCES campaign_recipients (organization_id, id) ON DELETE CASCADE;
ALTER TABLE bulk_category_job_items ADD CONSTRAINT bulk_category_job_items_job_id_org_fkey FOREIGN KEY (organization_id, job_id) REFERENCES bulk_category_jobs (organization_id, id) ON DELETE CASCADE;
ALTER TABLE campaign_recipients ADD CONSTRAINT campaign_recipients_campaign_id_org_fkey FOREIGN KEY (organization_id, campaign_id) REFERENCES campaigns (organization_id, id) ON DELETE CASCADE;
ALTER TABLE campaign_recipients ADD CONSTRAINT campaign_recipients_media_asset_id_org_fkey FOREIGN KEY (organization_id, media_asset_id) REFERENCES media_assets (organization_id, id) ON DELETE SET NULL (media_asset_id);
ALTER TABLE origens_migration_simulation_items ADD CONSTRAINT origens_migration_simulation_items_simulation_id_org_fkey FOREIGN KEY (organization_id, simulation_id) REFERENCES origens_migration_simulations (organization_id, id) ON DELETE CASCADE;
ALTER TABLE integration_secrets ADD CONSTRAINT integration_secrets_integration_id_org_fkey FOREIGN KEY (organization_id, integration_id) REFERENCES integrations (organization_id, id) ON DELETE CASCADE;
